import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  subsets: ['latin'],
  variable: "--font-poppins",
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "EventExpress",
  description: "Generated by create next app",
  icons: {
    icon: 'assets/images/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={poppins.variable}
          >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
